import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "@/app/_styles/globals.css";
import Header from "@/app/_components/Header";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "The wild oasis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body
        className={`relative min-h-full flex flex-col bg-primary-950 text-primary-100 ${josefin.className}`} // josefin.className is the font style
      >
        <Header />

        <div className="flex-1 px-8 py-12 ">
          <main className="max-w-7xl mx-auto">{children}</main>
        </div>
        <footer>
          <p>Copyright by the wild oasis</p>
        </footer>
      </body>
    </html>
  );
}
